[package]
name = "kassatypes"
version = "0.1.0"
authors = ["Sebastian <Sebastian@Strobl.net>"]
edition = "2018"

[lib]
name = "kassatypes"
path = "src/lib.rs"

[dependencies]
serde = { version = "1.0.125", features = ["derive"], optional = true }